### ISSUE TITLE
LICENSE VIOLATION

### ISSUE THREAD

**Issue by equinusocio** [Codextor/zed-material-theme#1]
Hello, I'm gently let you know you'are violating Material Theme license. You are not allowed to republish the extension since the theme is not open-source and is a pay extension.

https://github.com/material-theme/vsc-material-theme/blob/main/LICENSE

We give you 1 week to unpublished the extension from the Zed's extension marketplace, in the meanwhile we [contacted Zed Team](https://github.com/zed-industries/extensions/issues/1645) (and the [extension marketplace](https://github.com/zed-industries/extensions/issues/1644)) and Github team to ask for force removal. 

Thank you.

**Comment by twnlink** [comment]
This is not a republishing of your intellectual property but rather a separate work that uses colors that your intellectual property also happens to use. This is not violating any license.

**Comment by equinusocio** [comment]
There is a clear violation of the software license, which is linked. I will respond only the extension author now. Have a nice day.

**Comment by marshift** [comment]
You updated your license file to include the point about "for Visual Studio Code *or other software*" only an hour ago in [this commit](https://github.com/material-theme/vsc-material-theme/commit/b328d99ca5fe79b51c7ac8dac0ce92a6c00f4c82) shortly before making this issue. This further invalidates your claim.

**Comment by equinusocio** [comment]
That's not the repo of the software.

**Comment by marshift** [comment]
Also, this is very clearly an attempt to replace Codextor's version with your own "official" version, as seen [here](https://github.com/zed-industries/extensions/pull/1647). Quite pathetic, honestly.

**Comment by equinusocio** [comment]
Replace what, it has a different name. Another fail.

**Comment by marshift** [comment]
> That's not the repo of the software, is the repo of the deprecated free version. Fail.

Doesn't seem very deprecated considering you updated it an hour ago *specifically for this issue*, friend.

**Comment by equinusocio** [comment]
I updated the licese file which is not distributed with the extension/sowftware since is deprecated and not updated. No changes made to the software itself. Another fail. Stop wasting my time and have a nice day.

**Comment by marshift** [comment]
You're... still updating it though. And linking to it as your license. You know edits are public on here? You quite literally cited *that license* as your source of infringement, then edited it away when you realised you were wrong.

**Comment by equinusocio** [comment]
The only LICESE applied is the one distributed with the software, which is closed source. You can see it only when using the software, that one still the same license linked. My previos edit is made on an empty repository. 

The only way to link a license of a closed-source software is to made the license itself public (which was outdated on the deprecated version of the software).

Stop failing.

**Comment by marshift** [comment]
I mean comment edits, not repo commits. We can see those, including where you link *to your "deprecated" repo* in your original issue comment.

**Comment by equinusocio** [comment]
Yes, because not everyone uses vscode and knows we have two versions, and one is deprecated. So i made it clear for everyone. Anything else to argue about?

**Comment by marshift** [comment]
Think what you want to, I suppose, but it's very obvious that you're just trying to replace Codextor's perfectly fine theme with your own by adding bogus, hyperspecific claims to your license specifically so this issue can be made. But whatever, it's clear your mind won't change, so we'll see what the Zed folk think.
Have a nice day, friend.

**Comment by Codextor** [comment]
@equinusocio  I'll respond to the alleged license violation in the next comment.
But before we go there, I'd like to thank you for the work you did on the Material Theme extensions for Sublime Text and Visual Studio Code.
I came across them years ago and tried them out. I liked them so much that when I wanted to create a new theme for the Notepad++ editor, I took inspiration from the colour scheme of your extensions, as mentioned in the README file for the theme.
That was back in January 2018. The theme I created is still available [here](https://github.com/Codextor/npp-material-theme) and your color scheme had a significant influence on how it turned out. If memory serves, the colour scheme of your theme used to be available on your GitHub repository back in those days. A lot has changed since then. In fact, the GitHub repository for the Material Theme extension for Sublime Text no longer exists, and the one for Visual Studio Code has been overhauled.

**Comment by Codextor** [comment]
@equinusocio Coming to the alleged license violation, let me start by specifying a few things:
1. The Zed editor extension contained in this repository takes inspiration from the colour scheme of the [Material Theme — Free](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) extension available for Visual Studio Code.
2. The exact version of the Material Theme — Free extension in question is version 34.7.5, which was the latest version available on the Visual Studio Code marketplace at the time of creating this extension - 16 October 2024.
3. Material Theme — Free extension version 34.7.5 does come with a LICENSE.txt file. Since Visual Studio Code allows you to install specific versions of an extension, the content of the LICENSE.txt file for version 34.7.5 of the extension is available for review. I'm attaching the LICENSE.txt file for version 34.7.5 in this comment for ease of access, but its content can be verified by others if needed.
[LICENSE.txt](https://github.com/user-attachments/files/17837503/LICENSE.txt)

- Based on the applicable license for Material Theme — Free version 34.7.5, I disagree that the extension in this repository violates it. It does not republish the Material Theme — Free extension version 34.7.5 as claimed in the first comment. Instead, it takes inspiration from the colours used in Material Theme — Free extension version 34.7.5, as is already mentioned in the README file.
- I have noted that the license file you've referenced in your comments does not match the version of the license that comes with Material Theme — Free extension version 34.7.5. You also stated, *"The only LICENSE applied is the one distributed with the software"*. You have made references to clauses in the license (e.g. 2.d) that don't exist in the license shipped with Material Theme — Free extension version 34.7.5. This is misleading for anyone reviewing this issue page, and others in the thread have already pointed out the same problem.
- As someone who has been inspired by your work in the past, I was saddened to see that instead of contacting me to resolve the issue of my extension already existing on the extension marketplace of Zed editor, you took an aggressive approach by claiming license violation. Going as far as contacting the Zed and GitHub teams for forced removal, as mentioned in your first comment. Regardless, I had no intention of violating the license of the Material Theme — Free extension version 34.7.5. Since both Zed and GitHub teams have already been involved, I'd abide by the decision they come up with, even if it requires removal of the extension and/or its corresponding code.

**Comment by Codextor** [comment]
I'd like to thank @twnlink, @marshift, and others for their support of my theme through comments and reactions. It meant a lot to me and is the reason I decided to write a long response instead of simply complying with the takedown request.

I took a long time to respond as there were a lot of edits happening to comments and referenced files, and I wanted to wait for things to settle down. My response was based on comments and referenced files as of 20 November 2024, 22:00 UTC.

**Comment by equinusocio** [comment]
This is the only answer you will get:
## Point 1
You are using the same name, same colors, same color combinations, same variants names, Even the same preview screenshots. **This is not taking inspiration.**

## Point 2
From the license YOU mentioned, you are violating the following points.

> 1. ...The user is not authorized to _modify_, _distribute_, resell, or rent the extension _without the written consent of the author._
> 2. Restrictions
   The user may not:
   a) Reverse engineer, modify, decompile, or disassemble the extension's source code.
   b) Use the extension for illegal or unauthorized activities.
   c) Share the extension through channels other than the official sales channel.
> 4. Intellectual Property
   Mattia Astorino holds all rights, titles, and interests related to the extension, including but not limited to copyright, patents, trademarks, and trade secrets.


- 1 — You dind't asked for any authorization to re-distribuite the extension.
- 2.1 — By distributing it with the same name, but open source, you'are actually changing the extension.
- 2.c — You are sharing/distributing the extension as open source through non-official sales channels.
- 4 — By using the same name, colors, color combinations, screenshots, variants name your

Lastly, forking and distributing other people licensed code doesn't make it yours. Want to keep your extension? Change name, variants name, screenshots, and keep reference to the original Material Theme. Easy solution.

**Comment by Ivoz** [comment]
A maintainer might prefer to clarify that the project is based off a previous Apache 2.0 licensed version of Material theme, and further propagates that license. Thus, no arguments about compatibility with a newer license need be entertained.

Any Apache licensed distribution, as coming from the original source, enjoys a **full, perpetual, irrevocable copyright and patent license** for any applicable code and content from the original author(s).

You can find for example, a 34.4.0 release of Material Theme, with a full Apache license, at [this commit tree](https://github.com/material-theme/vsc-material-theme/tree/0c9892823accd22589695f04af2fc25dd6f3a137), or in the case that becomes mysteriously unavailable, a similar one such as [here](https://github.com/Dramaga11/vsc-material-theme/tree/0c9892823accd22589695f04af2fc25dd6f3a137) or in the archived zip file 
[vsc-material-theme-0c9892823accd22589695f04af2fc25dd6f3a137.zip](https://github.com/user-attachments/files/18269902/vsc-material-theme-0c9892823accd22589695f04af2fc25dd6f3a137.zip)

**Comment by nicc777** [comment]
I'll just leave this here.... https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users

**Comment by mirzap** [comment]
@equinusocio In addition to what others mentioned earlier, who pointed out that the theme was previously licensed under the Apache License—one of the most open licenses available—and that you lied when stating the theme did not have any contributors, you do not own the trademark on the "Material Theme" name, so you have no claim on the theme/plugin name either. It's not yours! 

Congrats on nuking your successful OSS project. I'll make sure to maintain the OSS version starting from [0c9892823](https://github.com/material-theme/vsc-material-theme/tree/0c9892823accd22589695f04af2fc25dd6f3a137)

**Comment by HalanoSiblee** [comment]
we have 16,777,216 hex color available, so pick a number fast easy money
I choose white so :
Any one use the color `#ffffff` will be sued it's licensed

**Comment by ar1ja** [comment]
this is the stupidest shit ive ever heard someone say, and ive heard some pretty stupid shit in my life

congrats 🎉

**Comment by AjayShanker-geek** [comment]
Found a community driven Google's Material UI theme under Apache License 2.0. https://github.com/t3dotgg/vsc-material-but-i-wont-sue-you 

Thanks @t3dotgg

**Comment by broman** [comment]
man i love github sometimes

**Comment by HauberDevs** [comment]
dang what a clown

**Comment by user1126s** [comment]
Well, its great that this issue was resolved!
